apiVersion: v1
kind: ConfigMap
metadata:
  name: silver-guardian-backend-config
  namespace: silver-guardian
data:
  DB_HOST: "silver-guardian-db.c9osquca0esm.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "silver_guardian"
  DB_USER: "dev"
  REDIS_HOST: "silver-guardian-redis.silver-guardian.svc.cluster.local"
  REDIS_PORT: "6379"
  GEMINI_MODEL: "gemini-2.0-flash"
---
apiVersion: v1
kind: Secret
metadata:
  name: silver-guardian-backend-secrets
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: "ZGV2cGFzczEyMw==" 
  GEMINI_API_KEY: "QUl6YVN5QzJQSnRWcEtWWkpYNzRqaDFXT2Qwb3lxYkNURDN4Q0hr"    
  YOUTUBE_API_KEY: "QUl6YVN5RGdfV2dQLVRFWkpTYlZMRi1PZm1jUTdfbVA4bkMtanJv"   
